### ISSUE TITLE
tracking issue for doc changes edp1.2+

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-document-generation-templates#67]
Tracking changes to docs:

- [ ] SSDS - gamp3 / 4 - code review 
- [x] SSDS - gamp3 / 4 - interfaces (missing doc chapters)
- [ ] SSDS - gamp 3 / 4  - modules to be developed, interfaces between modules
- [ ] SSDS - gamp 3 / 4 - system data
- [ ]

**Comment by clemensutschig** [comment]
examples from SSDS / Gamp4 :)

```
			<h4><span>3.2.2</span> Interfaces between Modules</h4>
			<p>N/A</p>
			<h4><span>3.2.3</span> Interfaces to External Systems</h4>
			<p>N/A</p>
			<h4><span>3.2.4</span> System Diagram</h4>
			<p>N/A</p>
```

**Comment by clemensutschig** [comment]
@metmajer - we should fix this asap in a  joint session

**Comment by clemensutschig** [comment]
TIP - section 6 - needs to change for non-installed components:

```
        <p>Each component comes with individual installation tests. For details look in the Technical Installation Report.</p>
        {{#each data.repositories}}
        <h3>Component {{id}}</h3>

        <table class="no-page-break">
            <tr>
                <th class="lean">Step</th>
                <th class="content-wrappable">Instruction for Testing</th>
                <th class="content-wrappable">Expected Result</th>
                <th class="content-wrappable">Actual Result</th>
                <th class="lean">Pass / Fail</th>
            </tr>
            <tr>
                <td class="lean">1</td>
                <td class="content-wrappable">Component has been deployed and individual installation tests ran.</td>
                <td class="content-wrappable">Component has been successfully deployed. All installation tests ran successfully.</td>
                <td class="content-wrappable">N/A</td>
                <td class="content-wrappable">N/A</td>
            </tr>
```
